// <auto-generated />
namespace trabFinal_Misael_Gabriel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class separacaodastablesdelog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(separacaodastablesdelog));
        
        string IMigrationMetadata.Id
        {
            get { return "201711271953597_separacaodastablesdelog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
